server:
  port: 8120 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    keyid: LTAI5t9GrWMJPCUubphnsLm7
    keysecret: MjwsBRT3mgarKthAGWou2gzJ3a4Xpq
    #bucket可以在控制台创建，也可以使用java代码创建，注意先测试bucket是否已被占用
    bucketname: cloud-file-230201-1
swagger:
  enable: true